var abbreviations = {
  "AEB": "Brazilian Space Agency",
  "ATV": "All-Terrain Vehicle",
  "AWESOM": "Autonomous Water Extraction from the Surface Of Mars",
  "CEO": "Chief Executive Officer",
  "CIGS": "Copper Indium Gallium Selenide",
  "CME": "Coronal Mass Ejection",
  "CNSA": "China National Space Administration",
  "COTS": "Commercial Off The Shelf",
  "CSA": "Canadian Space Agency",
  "DCS": "Decompression Sickness",
  "DRA": "Design Reference Architecture",
  "ECLSS": "Environment Control and Life Support System",
  "EDL": "Entry, Descent and Landing",
  "EELV": "Evolved Expendable Launch Vehicle",
  "EHA": "Extra-Habitat Activity",
  "EOI": "Earth Orbit Insertion",
  "EOR": "Earth Orbit Rendezvous",
  "ERV": "Earth Return Vehicle",
  "ESA": "European Space Agency",
  "EVA": "Extra-Vehicular Activity",
  "FMARS": "Flashline Mars Arctic Research Station",
  "GNC": "Guidance, Navigation and Control",
  "GPS": "Global Positioning System",
  "H2M": "Humans to Mars",
  "HLLV": "Heavy Lift Launch Vehicle",
  "IMRS": "International Mars Research Station",
  "ISA": "Iranian Space Agency",
  "ISAP": "In Situ Air Production",
  "ISFP": "In Situ Food Production",
  "ISPP": "In Situ Propellant Production",
  "ISRO": "Indian Space Research Organisation",
  "ISRU": "In Situ Resource Utilisation",
  "ISS": "International Space Station",
  "ISWP": "In Situ Water Production",
  "IT": "Information Technology",
  "IVA": "Intra-Vehicular Activity",
  "JAXA": "Japan Aerospace Exploration Agency",
  "KARI": "Korea Aerospace Research Institute",
  "L5CS": "L5 Communications Satellite",
  "LCH4": "Liquid Methane",
  "LED": "Light-Emitting Diode",
  "LH2": "Liquid Hydrogen",
  "LEO": "Low Earth Orbit",
  "LFTR": "Liquid Fluoride Thorium Reactor",
  "LION": "Landing with Inertial and Optical Navigation",
  "LOX": "Liquid Oxygen",
  "LPS": "Local Positioning System",
  "MARS": "Mars Analog Research Station",
  "MAV": "Mars Ascent Vehicle",
  "MCOS": "Mars Communications and Observation Satellite",
  "MDRS": "Mars Desert Research Station",
  "MLLV": "Medium Lift Launch Vehicle",
  "MOLA": "Mars Orbiting Laser Altimeter",
  "MOI": "Mars Orbit Insertion",
  "MOR": "Mars Orbit Rendezvous",
  "MSH": "Mars Surface Habitat",
  "MSV": "Mars Surface Vehicle",
  "MTH": "Mars Transit Habitat",
  "MTV": "Mars Transfer Vehicle",
  "NASA": "National Aeronautics and Space Administration",
  "NTR": "Nuclear Thermal Rocket",
  "PHP-M": "Permanent Human Presence on Mars",
  "PLSS": "Personal Life Support System",
  "PV": "Photovoltaic",
  "RCS": "Reaction Control System",
  "RH": "Relative Humidity",
  "ROI": "Return On Investment",
  "RP1": "Rocket Propellant 1",
  "RTG": "Radioisotope Thermoelectric Generator",
  "RWGS": "Reverse Water Gas Shift",
  "SLS": "Space Launch System",
  "SMAC": "Spacecraft Maximum Allowable Concentrations",
  "SP": "Special Publication",
  "TEI": "Trans Earth Injection",
  "TMI": "Trans Mars Injection",
  "TRL": "Technology Readiness Level",
  "USA": "United States of America",
  "VASIMR": "Variable Specific Impulse Magnetoplasma Rocket",
  "VTOL": "Vertical Take-Off and Landing",
  "WAVAR": "Water Vapour Adsorption Reactor",
  "ZPB": "Zero Prebreathe"
};

var formulae = {
  "Ar": "argon",
  "CH4": "methane",
  "CH3OH": "methanol",
  "CO": "carbon monoxide",
  "CO2": "carbon dioxide",
  "H2": "hydrogen",
  "H2O": "water",
  "Kr": "krypton",
  "O2": "oxygen",
  "O3": "ozone",
  "N2": "nitrogen",
  "Ne": "neon",
  "NH3": "ammonia",
  "NO": "nitric oxide",
  "NO2": "nitrogen dioxide",
  "Xe": "xenon"
};
