var abbreviations = {
  "AEB": "Brazilian Space Agency",
  "AG": "Artificial Gravity",
  "ATV": "All-Terrain Vehicle",
  "AWESOM": "Autonomous Water Extraction from the Surface Of Mars",
  "BP": "Bundle Protocol",
  "CCD": "Charge-Coupled Device",
  "CEO": "Chief Executive Officer",
  "CIGS": "Copper Indium Gallium Selenide",
  "CME": "Coronal Mass Ejection",
  "CNSA": "China National Space Administration",
  "COTS": "Commercial Off The Shelf",
  "CSA": "Canadian Space Agency",
  "DCS": "Decompression Sickness",
  "DRA": "Design Reference Architecture",
  "DSN": "Deep Space Network",
  "DTN": "Delay/Disruption Tolerant Networking",
  "ECLSS": "Environment Control and Life Support System",
  "EDL": "Entry, Descent and Landing",
  "EELV": "Evolved Expendable Launch Vehicle",
  "EHA": "Extra-Habitat Activity",
  "EOI": "Earth Orbit Insertion",
  "EOR": "Earth Orbit Rendezvous",
  "ERV": "Earth Return Vehicle",
  "ESA": "European Space Agency",
  "EVA": "Extra-Vehicular Activity",
  "FMARS": "Flashline Mars Arctic Research Station",
  "GNC": "Guidance, Navigation and Control",
  "GPS": "Global Positioning System",
  "H2M": "Humans to Mars",
  "HD": "High Definition",
  "HiRISE": "High Resolution Imaging Science Experiment",
  "HLLV": "Heavy Lift Launch Vehicle",
  "IMRS": "International Mars Research Station",
  "IP": "Internet Protocol",
  "ISA": "Iranian Space Agency",
  "ISAP": "In Situ Air Production",
  "ISFP": "In Situ Food Production",
  "ISPP": "In Situ Propellant Production",
  "ISRO": "Indian Space Research Organisation",
  "ISRU": "In Situ Resource Utilisation",
  "ISS": "International Space Station",
  "ISWP": "In Situ Water Production",
  "IT": "Information Technology",
  "IVA": "Intra-Vehicular Activity",
  "JAXA": "Japan Aerospace Exploration Agency",
  "KARI": "Korea Aerospace Research Institute",
  "LCRS": "Lagrangian point 5 (L5) Communications Relay Satellite",
  "LCH4": "Liquid Methane",
  "LED": "Light-Emitting Diode",
  "LH2": "Liquid Hydrogen",
  "LEO": "Low Earth Orbit",
  "LFTR": "Liquid Fluoride Thorium Reactor",
  "LION": "Landing with Inertial and Optical Navigation",
  "LNG": "Liquid Natural Gas",
  "LOC": "Loss Of Crew",
  "LOM": "Loss Of Mission",
  "LOX": "Liquid Oxygen",
  "LPS": "Local Positioning System",
  "MARS": "Mars Analog Research Station",
  "MAV": "Mars Ascent Vehicle",
  "MC": "Mission Control",
  "MCOS": "Mars Communication and Observation Satellite",
  "MDRS": "Mars Desert Research Station",
  "MEV": "Mars Exploration Vehicle",
  "MGS": "Mars Global Surveyor",
  "MLLV": "Medium Lift Launch Vehicle",
  "MOLA": "Mars Orbiting Laser Altimeter",
  "MOI": "Mars Orbit Insertion",
  "MOR": "Mars Orbit Rendezvous",
  "MRO": "Mars Reconnaissance Orbiter",
  "MSH": "Mars Surface Habitat",
  "MTH": "Mars Transit Habitat",
  "MTV": "Mars Transfer Vehicle",
  "NASA": "National Aeronautics and Space Administration",
  "NDS": "NASA Docking System",
  "NTR": "Nuclear Thermal Rocket",
  "PHP-M": "Permanent Human Presence on Mars",
  "PLSS": "Personal Life Support System",
  "PV": "Photovoltaic",
  "RCS": "Reaction Control System",
  "RH": "Relative Humidity",
  "ROI": "Return On Investment",
  "RP1": "Rocket Propellant 1",
  "RTG": "Radioisotope Thermoelectric Generator",
  "RWGS": "Reverse Water Gas Shift",
  "SLS": "Space Launch System",
  "SMAC": "Spacecraft Maximum Allowable Concentrations",
  "SN": "Space Network",
  "SP": "Special Publication",
  "TCP": "Transmission Control Protocol",
  "TDRS": "Tracking and Data Relay Satellite",
  "TDRSS": "Tracking and Data Relay Satellite System",
  "TEI": "Trans Earth Injection",
  "TMI": "Trans Mars Injection",
  "TRL": "Technology Readiness Level",
  "USA": "United States of America",
  "VASIMR": "Variable Specific Impulse Magnetoplasma Rocket",
  "VTOL": "Vertical Take-Off and Landing",
  "WAVAR": "Water Vapour Adsorption Reactor",
  "ZPB": "Zero Prebreathe"
};

var formulae = {
  "Ar": "argon",
  "C": "carbon",
  "CH4": "methane",
  "CH3OH": "methanol",
  "CO": "carbon monoxide",
  "CO2": "carbon dioxide",
  "H": "hydrogen",
  "H2": "hydrogen",
  "H2O": "water",
  "Kr": "krypton",
  "O": "oxygen",
  "O2": "oxygen",
  "O3": "ozone",
  "N2": "nitrogen",
  "Ne": "neon",
  "NH3": "ammonia",
  "NO": "nitric oxide",
  "NO2": "nitrogen dioxide",
  "Xe": "xenon"
};
