<?php
/**
 * @file imrs_misc.module
 * @author Shaun Moss (shaun@astromultimedia.com, skype:mossy2100)
 * @since 15-Feb-2014 20:19
 */

function imrs_misc_init() {
  require_once DRUPAL_ROOT . "/sites/all/libraries/star/php/strings.php";
  require_once DRUPAL_ROOT . "/sites/all/libraries/star/php/arrays.php";

  dbg_on();

  drupal_add_js(drupal_get_path('module', 'imrs_misc'). '/acronyms.js');
  drupal_add_js(drupal_get_path('module', 'imrs_misc'). '/imrs_misc.js');
  drupal_add_js("sites/all/libraries/jquery/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.js");
  drupal_add_css("sites/all/libraries/jquery/jquery-ui-1.10.4.custom/css/smoothness/jquery-ui-1.10.4.custom.css");
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 *
 * @param array $settings
 * @param array $context
 */
function imrs_misc_wysiwyg_editor_settings_alter(&$settings, $context) {
  // Turn off the Advanced Content Filter:
  $settings['allowedContent'] = TRUE;
}

/**
 * Implement hook_menu_alter().
 */
function imrs_misc_menu_alter(&$items) {
  // Remove register and password forms so no-one can join:
  unset($items['user/register']);
  unset($items['user/password']);
}
