<?php
/**
 * @file imrs_misc.module
 * @author Shaun Moss (shaun@astromultimedia.com, skype:mossy2100)
 * @since 15-Feb-2014 20:19
 */

function imrs_misc_init() {
  require_once DRUPAL_ROOT . "/sites/all/libraries/star/php/strings.php";
  require_once DRUPAL_ROOT . "/sites/all/libraries/star/php/arrays.php";
  require_once DRUPAL_ROOT . "/sites/all/libraries/star/php/objects.php";

  dbg_on();

  drupal_add_js(drupal_get_path('module', 'imrs_misc'). '/imrs_misc.js');
  drupal_add_js([
    'elements' => imrs_misc_elements(),
    'compounds' => imrs_misc_compounds(),
    'acronyms' => imrs_misc_acronyms(),
  ], 'setting');

  drupal_add_js("sites/all/libraries/jquery/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.js");
  drupal_add_css("sites/all/libraries/jquery/jquery-ui-1.10.4.custom/css/smoothness/jquery-ui-1.10.4.custom.css");
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 *
 * @param array $settings
 * @param array $context
 */
function imrs_misc_wysiwyg_editor_settings_alter(&$settings, $context) {
  // Turn off the Advanced Content Filter:
  $settings['allowedContent'] = TRUE;
}

/**
 * Implement hook_menu_alter().
 */
function imrs_misc_menu_alter(&$items) {
  // Remove register and password forms so no-one can join:
  unset($items['user/register']);
  unset($items['user/password']);
}

/**
 * Implements hook_block_info().
 */
function imrs_misc_block_info() {
  $blocks = [];
  $blocks['contents'] = [
    'info' => t('IMRS Book Contents'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    'properties' => [
      'administrative' => FALSE,
    ]
  ];
  return $blocks;
}

/**
 * Generate the TOC subblock for the given level.
 *
 * @param int $level
 * @param int $plid
 * @param string $parent_section
 * @return string
 */
function _imrs_misc_toc($level = 0, $plid = 0, $parent_section = '') {
  $html = '';
  $q2 = "select * from menu_links where plid=$plid and menu_name='book-toc-1' order by weight";
  $rs2 = db_query($q2);
  if ($rs2->rowCount()) {
    $html .= "<div id='section-level-$level'>";
    $n = 1;
    foreach ($rs2 as $rec2) {
      $section_number = $plid ? ($parent_section . $n . '.') : '';
      $section = $plid ? ($section_number . ' ') : '';
      $margin = $plid ? ($level * 10 - 10) : 3;
//      $options = (current_path() == $rec2->link_path) ? ['attributes' => ['class' => ['active']]] : [];
      $options = [];
      $html .= "<div class='section-item' style='margin-left:{$margin}px'>";
      $html .= "<div class='section-link'>{$section}". l($rec2->link_title, $rec2->link_path, $options) . "</div>";
      $html .= _imrs_misc_toc($level + 1, $rec2->mlid, $section_number);
      $html .= "</div>"; // section
      $n++;
    }
    $html .= "</div>";
  }
  return $html;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 * @return string
 */
function imrs_misc_block_view($delta = '') {
  $block = [];
  if ($delta == 'contents') {
    $block['subject'] = 'Contents';
    $block['content'] = _imrs_misc_toc();
  }
  return $block;
}

function imrs_misc_elements() {
  return [
    'Ar' => 'argon',
    'C' => 'carbon',
    'H' => 'hydrogen',
    'Kr' => 'krypton',
    'O' => 'oxygen',
    'N' => 'nitrogen',
    'Ne' => 'neon',
    'Xe' => 'xenon',
  ];
}

function imrs_misc_compounds() {
  return [
    'CH4' => 'methane',
    'CH3OH' => 'methanol',
    'CO' => 'carbon monoxide',
    'CO2' => 'carbon dioxide',
    'H2' => 'hydrogen',
    'H2O' => 'water',
    'O2' => 'oxygen',
    'O3' => 'ozone',
    'N2' => 'nitrogen',
    'NH3' => 'ammonia',
    'NO' => 'nitric oxide',
    'NO2' => 'nitrogen dioxide',
  ];
}

function imrs_misc_acronyms() {
  return [
    'AEB' => 'Agência Espacial Brasileira (Brazilian Space Agency)',
    'AG' => 'Artificial Gravity',
    'ATV' => 'All-Terrain Vehicle',
    'AWESOM' => 'Autonomous Water Extraction from the Surface Of Mars',
    'BP' => 'Bundle Protocol',
    'BPS' => 'Ballistic Protection System',
    'CCD' => 'Charge-Coupled Device',
    'CDR' => 'Commander',
    'CEO' => 'Chief Executive Officer',
    'CIGS' => 'Copper Indium Gallium Selenide',
    'CME' => 'Coronal Mass Ejection',
    'CNSA' => 'China National Space Administration',
    'COTS' => 'Commercial Off The Shelf',
    'CSA' => 'Canadian Space Agency',
    'DCS' => 'Decompression Sickness',
    'DRA' => 'Design Reference Architecture',
    'DRM' => 'Design Reference Mission',
    'DS' => 'Deep Space',
    'DSN' => 'Deep Space Network',
    'DTN' => 'Delay/Disruption Tolerant Networking',
    'ECLSS' => 'Environment Control and Life Support System',
    'EDL' => 'Entry, Descent and Landing',
    'EELV' => 'Evolved Expendable Launch Vehicle',
    'EHA' => 'Extra-Habitat Activity',
    'EOI' => 'Earth Orbit Insertion',
    'EOR' => 'Earth Orbit Rendezvous',
    'ERV' => 'Earth Return Vehicle',
    'ESA' => 'European Space Agency',
    'ETO' => 'Earth To Orbit',
    'EVA' => 'Extra-Vehicular Activity',
    'FMARS' => 'Flashline Mars Arctic Research Station',
    'G-FOLD' => 'Guidance for Fuel Optimal Large Diverts',
    'GNC' => 'Guidance, Navigation and Control',
    'GPS' => 'Global Positioning System',
    'H2L' => 'Humans to Luna',
    'H2M' => 'Humans to Mars',
    'HD' => 'High Definition',
    'HiRISE' => 'High Resolution Imaging Science Experiment',
    'HLLV' => 'Heavy Lift Launch Vehicle',
    'ICT' => 'Information and Communications Technology',
    'IMRS' => 'International Mars Research Station',
    'IP' => 'Internet Protocol',
    'ISA' => 'Iranian Space Agency',
    'ISAP' => 'In Situ Air Production',
    'ISEP' => 'In Situ Electricity Production',
    'ISFP' => 'In Situ Food Production',
    'ISPP' => 'In Situ Propellant Production',
    'ISRO' => 'Indian Space Research Organisation',
    'ISRU' => 'In Situ Resource Utilisation',
    'ISS' => 'International Space Station',
    'ISWP' => 'In Situ Water Production',
    'IT' => 'Information Technology',
    'IVA' => 'Intra-Vehicular Activity',
    'JAXA' => 'Japan Aerospace Exploration Agency',
    'JSA' => 'Job Safety Analysis',
    'KARI' => 'Korea Aerospace Research Institute',
    'LCRS' => 'Lagrangian point 5 (L5) Communications Relay Satellite',
    'LCH4' => 'Liquid Methane',
    'LED' => 'Light-Emitting Diode',
    'LEO' => 'Low Earth Orbit',
    'LFTR' => 'Liquid Fluoride Thorium Reactor',
    'LH2' => 'Liquid Hydrogen',
    'LION' => 'Landing with Inertial and Optical Navigation',
    'LNG' => 'Liquid Natural Gas',
    'LMO' => 'Low Mars Orbit',
    'LOC' => 'Loss Of Crew',
    'LOM' => 'Loss Of Mission',
    'LOX' => 'Liquid Oxygen',
    'LPS' => 'Local Positioning System',
    'LZ' => 'Landing Zone',
    'MARS' => 'Mars Analog Research Station',
    'MAS' => 'Mars Activity Suit',
    'MAV' => 'Mars Ascent Vehicle',
    'MCC' => 'Mission Control Centre',
    'MCOS' => 'Mars Communication and Observation Satellite',
    'MCP' => 'Mechanical Counter-Pressure',
    'MDRS' => 'Mars Desert Research Station',
    'MDS' => 'Modified Deep Space',
    'MER' => 'Mars Exploration Rover',
    'MEV' => 'Mars Exploration Vehicle',
    'MGS' => 'Mars Global Surveyor',
    'MIT' => 'Massachusetts Institute of Technology',
    'MLLV' => 'Medium Lift Launch Vehicle',
    'MOI' => 'Mars Orbit Insertion',
    'MOLA' => 'Mars Orbiting Laser Altimeter',
    'MOR' => 'Mars Orbit Rendezvous',
    'MRO' => 'Mars Reconnaissance Orbiter',
    'MSA' => 'Mars Society Australia',
    'MSH' => 'Mars Surface Habitat',
    'MSL' => 'Mars Science Laboratory',
    'MTH' => 'Mars Transit Habitat',
    'MTV' => 'Mars Transfer Vehicle',
    'NASA' => 'National Aeronautics and Space Administration',
    'NDS' => 'NASA Docking System',
    'NTR' => 'Nuclear Thermal Rocket',
    'OMS' => 'Orbital Manoeuvring System',
    'OTE' => 'Orbit To Earth',
    'OTM' => 'Orbit To Mars',
    'PHP-L' => 'Permanent Human Presence on Luna',
    'PHP-M' => 'Permanent Human Presence on Mars',
    'PLSS' => 'Personal Life Support System',
    'PV' => 'Photovoltaic',
    'RCS' => 'Reaction Control System',
    'RH' => 'Relative Humidity',
    'RLS' => 'Reusable Launch System',
    'ROI' => 'Return On Investment',
    'RP1' => 'Rocket Propellant 1',
    'RPS' => 'Radiation Protection System',
    'RTG' => 'Radioisotope Thermoelectric Generator',
    'RWGS' => 'Reverse Water Gas Shift',
    'SAS' => 'Space Activity Suit',
    'SCUBA' => 'Self-Contained Underwater Breathing Apparatus',
    'SHLLV' => 'Super Heavy Lift Launch Vehicle',
    'SLS' => 'Space Launch System',
    'SMAC' => 'Spacecraft Maximum Allowable Concentrations',
    'SN' => 'Space Network',
    'SP' => 'Special Publication',
    'SGR' => 'Stirling Radioisotope Generator',
    'TBD' => 'To Be Determined',
    'TCP' => 'Transmission Control Protocol',
    'TDRS' => 'Tracking and Data Relay Satellite',
    'TDRSS' => 'Tracking and Data Relay Satellite System',
    'TEI' => 'Trans Earth Injection',
    'TMI' => 'Trans Mars Injection',
    'TPS' => 'Thermal Protection System',
    'TRL' => 'Technology Readiness Level',
    'USA' => 'United States of America',
    'UV' => 'Ultra-Violet',
    'VASIMR' => 'Variable Specific Impulse Magnetoplasma Rocket',
    'VTOL' => 'Vertical Take-Off and Landing',
    'WAVAR' => 'Water Vapour Adsorption Reactor',
    'ZPB' => 'Zero Prebreathe',
    'ZPS' => 'Zero Prebreathe Spacesuit',
  ];
}

function imrs_misc_abbr_table() {
  $elements = imrs_misc_elements();
  $header = ['Symbol', 'Element'];
  $rows = [];
  foreach ($elements as $abbr => $element) {
    $rows[] = [$abbr, $element];
  }
  $element_table = theme('table', ['header' => $header, 'rows' => $rows, 'sticky' => FALSE]);

  $compounds = imrs_misc_compounds();
  $header = ['Formula', 'Compound'];
  $rows = [];
  foreach ($compounds as $abbr => $compound) {
    $rows[] = [$abbr, $compound];
  }
  $compound_table = theme('table', ['header' => $header, 'rows' => $rows, 'sticky' => FALSE]);

  $acronyms = imrs_misc_acronyms();
  $header = ['Acronym', 'Meaning'];
  $rows = [];
  foreach ($acronyms as $abbr => $acronym) {
    $rows[] = [$abbr, $acronym];
  }
  $acronym_table = theme('table', ['header' => $header, 'rows' => $rows, 'sticky' => FALSE]);

  return "
    <h2>Chemical Elements</h2>
    $element_table

    <p>&nbsp;</p>

    <h2>Chemical Compounds</h2>
    $compound_table

    <p>&nbsp;</p>

    <h2>Acronyms</h2>
    $acronym_table
    ";
}
